/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:72b198a3-0334-4061-8bdf-246c583ca9b5",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_86ZemgUAF",
    "aws_user_pools_web_client_id": "aluu9k2i3cb48f29sub579fpk",
    "oauth": {}
};


export default awsmobile;
